### ISSUE TITLE
ASWM - Problem while loading island warps (during server startup)

### ISSUE THREAD

**Issue by xSavior-of-God** [BG-Software-LLC/SuperiorSkyblock2#1227]
### Minecraft's Version

1.16.2

### Plugin's Version

Dev #706

### Describe the bug

When loading islands, the server fails to generate island warps because the world is not loaded (via ASWM)

```YAML
[22:32:52 INFO]: [SuperiorSkyblock2] Finished loading 2 players (Took 10ms)
[22:32:52 INFO]: [SuperiorSkyblock2] Starting to load islands...
[22:32:52 WARN]: java.lang.NullPointerException: location's world cannot be null.
[22:32:52 WARN]:        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.createWarp(SIsland.java:2625)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$loadFromCachedInfo$122(SIsland.java:3581)
[22:32:52 WARN]:        at java.util.ArrayList.forEach(ArrayList.java:1259)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.loadFromCachedInfo(SIsland.java:3575)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.fromDatabase(SIsland.java:312)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.factory.FactoriesManagerImpl.createIsland(FactoriesManagerImpl.java:119)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:122)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.DataManager.lambda$loadIslands$2(DataManager.java:175)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$1(SQLDatabaseBridge.java:48)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:34)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.executeQuery(SQLiteSession.java:221)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.select(SQLiteSession.java:168)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.select(SQLHelper.java:85)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:45)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.DataManager.loadIslands(DataManager.java:174)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.DataManager.loadData(DataManager.java:69)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:517)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:253)
[22:32:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:32:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[22:32:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[22:32:52 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[22:32:52 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:303)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:32:52 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:32:52 WARN]: java.lang.NullPointerException: location's world cannot be null.
[22:32:52 WARN]:        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:787)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.createWarp(SIsland.java:2625)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.lambda$loadFromCachedInfo$122(SIsland.java:3581)
[22:32:52 WARN]:        at java.util.ArrayList.forEach(ArrayList.java:1259)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.loadFromCachedInfo(SIsland.java:3575)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.SIsland.fromDatabase(SIsland.java:312)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.factory.FactoriesManagerImpl.createIsland(FactoriesManagerImpl.java:119)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.island.GridManagerImpl.createIsland(GridManagerImpl.java:122)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.DataManager.lambda$loadIslands$2(DataManager.java:175)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.lambda$loadAllObjects$1(SQLDatabaseBridge.java:48)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.session.QueryResult.complete(QueryResult.java:34)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.executeQuery(SQLiteSession.java:221)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.session.impl.SQLiteSession.select(SQLiteSession.java:168)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.SQLHelper.select(SQLHelper.java:85)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.sql.SQLDatabaseBridge.loadAllObjects(SQLDatabaseBridge.java:45)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.DataManager.loadIslands(DataManager.java:174)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.core.database.DataManager.loadData(DataManager.java:69)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:517)
[22:32:52 WARN]:        at com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:253)
[22:32:52 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[22:32:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[22:32:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[22:32:52 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[22:32:52 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:303)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074)
[22:32:52 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[22:32:52 WARN]:        at java.lang.Thread.run(Thread.java:748)
[22:32:52 INFO]: [SuperiorSkyblock2] Finished loading 0 islands (Took 54ms)
```

### To Reproduce

- Create an island
- Set a warp
- Quit and restart the server

When you join after restarting the server, the island instance is "null"

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by xSavior-of-God** [comment]
Hi @OmerBenGera,
only today I had time to try the new version, but still the problem persists and in addition the server loads the island that has set a warp when it starts!

**Version 1.11.0-b731**

As soon as I entered, Superior did not recognize the islands, 
the error is the following
![image](https://user-images.githubusercontent.com/66216419/180625100-34cda8e2-95b0-420a-a83f-893c5fa34e7a.png)

![image](https://user-images.githubusercontent.com/66216419/180625124-c6c462bb-7bf3-4344-b39c-b50cfaacedf4.png)

**Comment by OmerBenGera** [comment]
> Hi @OmerBenGera, only today I had time to try the new version, but still the problem persists and in addition the server loads the island that has set a warp when it starts!
> 
> **Version 1.11.0-b731**
> 
> As soon as I entered, Superior did not recognize the islands, the error is the following ![image](https://user-images.githubusercontent.com/66216419/180625100-34cda8e2-95b0-420a-a83f-893c5fa34e7a.png)
> 
> ![image](https://user-images.githubusercontent.com/66216419/180625124-c6c462bb-7bf3-4344-b39c-b50cfaacedf4.png)

Fixed.

**Comment by xSavior-of-God** [comment]
Hi, thanks for the fix... 
Now the problem is solved, 
but there is another one:

When starting, you force the load of all **island worlds**, 
why, if I have more than 500 islands the server will never be able to start...
![image](https://user-images.githubusercontent.com/66216419/180643693-7211dfba-7e49-45d6-a63b-63d6ad6a0688.png)

**Comment by OmerBenGera** [comment]
> Hi, thanks for the fix... Now the problem is solved, but there is another one:
> 
> When starting, you force the load of all **island worlds**, why, if I have more than 500 islands the server will never be able to start... ![image](https://user-images.githubusercontent.com/66216419/180643693-7211dfba-7e49-45d6-a63b-63d6ad6a0688.png)

This is no longer required, you don't have to load the worlds anymore.
