### ISSUE TITLE
Update warp's location removes nearby sign

### ISSUE THREAD

**Issue by LeftCrosz** [BG-Software-LLC/SuperiorSkyblock2#1439]
### Minecraft's Version

Tacospigot 1.8.8

### Plugin's Version

b854

### Describe the bug

When I update my warp location it will remove nearby sign (about 1 block range) where I am standing. (This only occurred when you are standing really close to it)
![image](https://user-images.githubusercontent.com/40970486/198835612-db1f5c05-9066-45a5-a9e0-474c8344a4e4.png)

![image](https://user-images.githubusercontent.com/40970486/198835542-1af76e54-047d-4206-a190-6125c2051c90.png)

### To Reproduce

1. Stand really close to a sign
2. Use island warp settings menu to update warp location
![image](https://user-images.githubusercontent.com/40970486/198835612-db1f5c05-9066-45a5-a9e0-474c8344a4e4.png)
3. The nearby sign will get removed (This only occurred when you are standing really close to it)

### Additional Information

Even Unsafe warp in config is set to false

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by LeftCrosz** [comment]
![image](https://user-images.githubusercontent.com/40970486/198863148-66afe29f-2903-4438-b402-9684930282df.png)
The issue is not fixed. Tested with b891

**Comment by OmerBenGera** [comment]
> ![image](https://user-images.githubusercontent.com/40970486/198863148-66afe29f-2903-4438-b402-9684930282df.png) The issue is not fixed. Tested with b891

If the sign is warps sign it will break. Any other sign will nog

**Comment by LeftCrosz** [comment]
https://user-images.githubusercontent.com/40970486/198863888-7c48fc3e-f1f3-4578-a845-164aa4c84a11.mp4

It removes any sign.

**Comment by OmerBenGera** [comment]
Sorry about that, check out latest dev build
Let me know if it works now

**Comment by LeftCrosz** [comment]
Fixed. Thanks
