### ISSUE TITLE
Can't complete missions

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#1478]
### Minecraft's Version

git-Purpur-1839 (MC: 1.19.2)

### Plugin's Version

SuperiorSkyblock2 version 2022.9-b903

### Describe the bug

Clicking the icons in the missions menu does nothing

### To Reproduce

1. Upload mission file.
2. Restart server.
3. Complete Mission.
4. Click icon.

### Additional Information

https://www.mediafire.com/file/qj0sjc3qdx1tpob/sellitems.yml/file
https://www.mediafire.com/file/5nxvtepue3hnu28/SS2CommandMission.jar/file

**Comment by DuneSciFye** [comment]
Heres also a video of the issue: https://streamable.com/lqjvg1

**Comment by OmerBenGera** [comment]
Upload your missions to pastebin and send them here.

**Comment by OmerBenGera** [comment]
Upload your missions to pastebin and send them here.

**Comment by OmerBenGera** [comment]
Run `/is admin debug REWARD_MISSION`, then click a mission item.
Does it print anything to console?

**Comment by DuneSciFye** [comment]
Nothing

**Comment by OmerBenGera** [comment]
> Nothing

Does built-in mission jars work or they are bugged as well?

**Comment by DuneSciFye** [comment]
I believe built in mission jars work fine

**Comment by OmerBenGera** [comment]
> I believe built in mission jars work fine

It might be an issue with your custom mission then.
Mind sending me this jar so I can check it out?

**Comment by DuneSciFye** [comment]
It's in the additional information section

**Comment by OmerBenGera** [comment]
It worked fine for me.
Mind sharing with me your entire SSB folder, I will try to use your exact same setup

**Comment by DuneSciFye** [comment]
The entire folder is 2 GB, here's the config, missions folder, and menus attached
[SuperiorSkyblock2.zip](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/10099466/SuperiorSkyblock2.zip)

**Comment by DuneSciFye** [comment]
I found something, when first starting the server, it gives these errors when loading the missions: https://pastebin.com/Cdt2D0Ha

**Comment by DuneSciFye** [comment]
My enchanting missions are completely blank and throws these errors: https://pastebin.com/nNZZnzmb
![image](https://user-images.githubusercontent.com/65089425/204167119-1d3203c4-f71f-46bb-9329-9fca99a96796.png)

**Comment by OmerBenGera** [comment]
> I found something, when first starting the server, it gives these errors when loading the missions: https://pastebin.com/Cdt2D0Ha

Upload latest.log file to pastebin and send a link to it here

**Comment by DuneSciFye** [comment]
https://pastebin.com/jQJb5iq4

**Comment by OmerBenGera** [comment]
Update to latest dev build, let me know if it's fixed.
I fixed this warning a while ago, hopefully it fixes the issue.

**Comment by DuneSciFye** [comment]
The warnings are gone but the main issue is still here, clicking the island missions don't do anything. No errors in console either.

**Comment by OmerBenGera** [comment]
As I said before, it worked fine for me.
I'll need your folder to try and replicate it. I dont need the datastore folder, only the rest of the files. 
Zip them and upload to mediafire or any similar service.

**Comment by DuneSciFye** [comment]
I think I got it working.

**Comment by OmerBenGera** [comment]
> I think I got it working.

Awesome
What was the issue?
