### ISSUE TITLE
Is level are bug when we use cobblegenerator or tree

### ISSUE THREAD

**Issue by SkytraceXLSU** [BG-Software-LLC/SuperiorSkyblock2#1574]
### Minecraft's Version

Pufferfish 1.19.3-R0.1-SNAPSHOT

### Plugin's Version

SuperiorSkyblock2-2022.9-b960

### Describe the bug

we use jets minion and when they mine is level grow down and stairs  (show my is level )
![image](https://user-images.githubusercontent.com/78903583/215284613-9f450da7-7f3d-46b9-8639-cfdfd8f81eb6.png)

after do /is level rest this amount of is level
![image](https://user-images.githubusercontent.com/78903583/215284663-ff014e0b-110d-43cf-a68e-ef56f2c273c8.png)

### To Reproduce

use jets minions  and let miner work or lumberjack too

**Comment by Teyir** [comment]
Hello,

This issue is the same without minions.

**Comment by OmerBenGera** [comment]
It seems to only happen when you mine cobblestone, can you confirm this?

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it works

**Comment by SkytraceXLSU** [comment]
hey it's not work  is level grow again

**Comment by OmerBenGera** [comment]
> hey it's not work is level grow again

Take a video of the issue

**Comment by SkytraceXLSU** [comment]
https://youtu.be/0BDlSjrMsq8

**Comment by SkytraceXLSU** [comment]
I redo a new video later when is level are higher

**Comment by SkytraceXLSU** [comment]
Hey see this time is level are completely broke 
https://youtu.be/uqu1uATZmus

**Comment by SkytraceXLSU** [comment]
so is level when we connect disconnect return to 0  /spawn and do /is go reset to 0 too

**Comment by OmerBenGera** [comment]
Try it on a new island where you know exactly which blocks are broken and placed, as I can't understand anything from your videoes.

**Comment by SkytraceXLSU** [comment]
when the server restarts the is level is reset to 0, you have to do /is level to recover its level

**Comment by OmerBenGera** [comment]
> when the server restarts the is level is reset to 0, you have to do /is level to recover its level

Should be fixed with latest dev build.
Anyways not related to the error reported here.

**Comment by SkytraceXLSU** [comment]
no, but since we changed builds between as you said in the message above, we basically had the 2022.9-b960 to switch to the 2022.9-b972 as the bug had to be corrected but the bug remains the same and the is lvl was reset to 0 with this build

**Comment by OmerBenGera** [comment]
Use latest dev build, island levels will be fine.
If not, it means SGP did not load their shops data correctly, which is a known bug that doesn't seem to be related to SSB.

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by SkytraceXLSU** [comment]
hey so we are using SuperiorSkyblock2-2022.9-b977 is  level is already set to 0

**Comment by OmerBenGera** [comment]
> hey so we are using SuperiorSkyblock2-2022.9-b977 is level is already set to 0

What did you set in your worth-sync section in the config file?

**Comment by OmerBenGera** [comment]
Any news regarding this?

**Comment by OmerBenGera** [comment]
Closing this due to lack of response
If the issue continues let me know
