### ISSUE TITLE
CMILib Circular plugin

### ISSUE THREAD

**Issue by Teleriann** [BG-Software-LLC/SuperiorSkyblock2#1635]
### Minecraft's Version

Paper 1.19.3

### Plugin's Version

Newest dev build

### Describe the bug

This happends always on server start, when I put superiorskyblock plugin inside plugin folder.

https://pastebin.com/ZVQKe4nX

### To Reproduce

Just put CMI, CMIlib, which is a dependency and SuperiorSkyblock2 on server, and there you go. When I was using older versions some time ago, everything was fine. All plugins are on latest versions.

### Additional Information

Nothing really, all configs are default. Never saw this error. Could be problem of CMILib, i do not really know. But without superiorskyblock it works just fine.

**Comment by OmerBenGera** [comment]
Update Paper, it was fixed by them already.

**Comment by Teleriann** [comment]
I have updated paper to newest version, and the problem is still there. What am I doing wrong?

**Comment by OmerBenGera** [comment]
> I have updated paper to newest version, and the problem is still there. What am I doing wrong?

Contact them for support.
This should be fixed in newer versions of Paper. Also, this is not relates to SSB.

**Comment by Teleriann** [comment]
https://github.com/PaperMC/Paper/issues/8964

They told me this, I do not really know what to do.

**Comment by OmerBenGera** [comment]
Not an issue with SSB.
Add legacy plugin loading option as suggested and everything will work just fine as you were suggested
