### ISSUE TITLE
Offline time resets in /is team if joined vanished

### ISSUE THREAD

**Issue by exzolink** [BG-Software-LLC/SuperiorSkyblock2#1718]
### Minecraft's Version

1.16.5

### Plugin's Version

b18

### Describe the bug

Offline time resets in /is team if joined vanished (but still showing that player offline)
https://www.spigotmc.org/resources/supervanish-be-invisible.1331/

### To Reproduce

-

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by exzolink** [comment]
@OmerBenGera Not fully fixed, /is warp /is go still reset time

**Comment by OmerBenGera** [comment]
> @OmerBenGera Not fully fixed, /is warp /is go still reset time

Open a new issue regarding this
