### ISSUE TITLE
MissionCompleteEvent is not triggered on Mission completition

### ISSUE THREAD

**Issue by Davisiiiik** [BG-Software-LLC/SuperiorSkyblock2#1999]
### Minecraft's Version

This server is running SlimeWorldManager version git-SlimeWorldManager-15751 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3731381 on paper_upstream)

### Plugin's Version

2023.3-b138

### Describe the bug

`MissionCompleteEvent` is not trigger upon mission completition. Not even when there is specified in `config.yml` (`IslandLeaveEvent` in this config example works):
```yml
event-commands:
  IslandLeaveEvent:
  - bc %player% left because of %leave-cause%!
  MissionCompleteEvent:
  - bc %player% just completed a mission!
```

`MissionCompleteEvent` is also not trigger during the `IslandMissions` missions, when this is set in mission yaml config file (even though `success-check:` is set to `'true'` or not set at all):

```yml
mission-file: IslandMissions

events:
  - MissionCompleteEvent
```

### To Reproduce

Easiest way to reproduce is:
1. Set this in main `config.yml`:
```yml
event-commands:
  MissionCompleteEvent:
  - minecraft:tellraw @a {"text":"%player% has completed a mission!"}
```
2. Complete any mission (both options, by `/is admin mission <player> complete <mission>` command, or by simply fulfilling the mission requirements
3. Watch as the listeners are are not triggered

**Comment by OmerBenGera** [comment]
I used `/is admin mission <player-name> complete miner_1` and it worked fine for me.
The event commands is not triggered for MissionCompleteEvent, and I will look into fixing it.

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed.

**Comment by Davisiiiik** [comment]
`event-commands` are now triggered, but `IslandMissions` missions with `MissionCompleteEvent` listener are still not. Other event listeners in my mission work (using `success-check: 'true'` option, so I know the problem is not in success check).

**Comment by OmerBenGera** [comment]
> `event-commands` are now triggered, but `IslandMissions` missions with `MissionCompleteEvent` listener are still not. Other event listeners in my mission work (using `success-check: 'true'` option, so I know the problem is not in success check).

What are you trying to do...?
I don't think I want to allow MissionCompleteEvent in the IslandMissions, it may cause an endless loop

**Comment by Davisiiiik** [comment]
I am trying to do this:

I have all missions with option `island: true`, so they are bound to islands.
I want to give players permissions when they complete certain missions.

When a player completes `required-missions`, I need to give permission to all players on the island. Furthemore I need to give the permission to players who join the island later if the `required-missions` are already completed.

So I created missions giving permissions with this configuration:

```yaml
island: false
auto-reward: true

required-missions:
  - ExampleMission1
  - ExampleMission2

events:
  - MissionCompleteEvent
  - IslandJoinEvent

rewards:
  commands:
    - 'lp user %player% permission set superior.missions.example'
  ```
  
So when anyone on island completes `ExampleMission1` and `ExampleMission2`, every player on the island will automatically get completed this `player` mission and is rewarded the permission.

I dont know any other way to do it, so if you think I am misusing your plugin, how can I achieve this?

**Comment by OmerBenGera** [comment]
> I am trying to do this:
> 
> I have all missions with option `island: true`, so they are bound to islands. I want to give players permissions when they complete certain missions.
> 
> When a player completes `required-missions`, I need to give permission to all players on the island. Furthemore I need to give the permission to players who join the island later if the `required-missions` are already completed.
> 
> So I created missions giving permissions with this configuration:
> 
> ```yaml
> island: false
> auto-reward: true
> 
> required-missions:
>   - ExampleMission1
>   - ExampleMission2
> 
> events:
>   - MissionCompleteEvent
>   - IslandJoinEvent
> 
> rewards:
>   commands:
>     - 'lp user %player% permission set superior.missions.example'
> ```
> 
> So when anyone on island completes `ExampleMission1` and `ExampleMission2`, every player on the island will automatically get completed this `player` mission and is rewarded the permission.
> 
> I dont know any other way to do it, so if you think I am misusing your plugin, how can I achieve this?

Check out latest dev build, let me know if it works

**Comment by Davisiiiik** [comment]
Tested. Everything works great, thank you!
