### ISSUE TITLE
Cobblestone Generator spawn "invisible" blocks

### ISSUE THREAD

**Issue by ipermatti83** [BG-Software-LLC/SuperiorSkyblock2#2373]
### Minecraft's Version

Mc version: 1.21.4-188-main@8de7e35 (2025-03-03T16:59:40Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

### Plugin's Version

Version: 2024.4-b424
Dev Build

### Describe the bug

If you use a pickaxe with high Efficiency like Eff. 5, after a few times that you break the blocks from the Cobblestone Generator they start to become "invisible".
You can't see them, mine them or walk past or over them; but you can break blocks behind it without any problem.

### To Reproduce

Create a cobblestone generator with a lenght of 7 blocks, use a pickaxe with efficiency 5 or higher and breaks for like 5 minutes the block inside the generator. Some of them should become invisible and you can't mine them.
But if you use right-click on that invisible block or try to place a block in the same spot, that invisible block suddendly respawn.

### Additional Information

[Minecraft_2025.02.10_-_13.51.25.01.zip](https://github.com/user-attachments/files/19087435/Minecraft_2025.02.10_-_13.51.25.01.zip)

I've sent a video so you can easily understand the problem (the video is not mine but the issue is the same).

[config.txt](https://github.com/user-attachments/files/19087491/config.txt)

**Comment by WaterArchery** [comment]
I am also experiencing the same issue. I fixed it with commenting these lines and setting block with the Bukkit API.
SIsland Class -> generateBlock(Location location, Dimension dimension, boolean optimizeDefaultBlock) Method

![Image](https://github.com/user-attachments/assets/142348b7-8683-4310-8a7a-ac13c244b16f)

**Comment by OmerBenGera** [comment]
> I am also experiencing the same issue. I fixed it with commenting these lines and setting block with the Bukkit API. SIsland Class -> generateBlock(Location location, Dimension dimension, boolean optimizeDefaultBlock) Method
> 
> ![Image](https://github.com/user-attachments/assets/142348b7-8683-4310-8a7a-ac13c244b16f)

This may cause lag, so be aware.

I cannot seem to replicate the issue - are you able to replicate it on a server with only SSB installed?

**Comment by realgamerk** [comment]
Hello @OmerBenGera this issue is still ongoing on my networks, i dont really know how to explain it properly
but in short the blocks is there, but they are not spawning in the eyes of the players, they will just pop out
like 3-10 minutes and i think its a visual issue from the plugin itself, i used latest version of 1.21.4 papermc
and version b436 in your latest dev build, i hope this helps thank you very much

**Comment by bogdanW11** [comment]
bump

**Comment by bogdanW11** [comment]
I have used Paper 1.21.4 and also switched to purpur latest 1.21.4, and I had the same issue on both.

**Comment by Yiiitt** [comment]
@OmerBenGera I experienced the error again on a Pufferfish 1.21.3 server with only the SuperiorSkyblock build #442 plugin, and I recorded it on video.
https://youtu.be/_YsMNGm-7Sg

**Comment by Viivtor** [comment]
I use paper 1.21.1
Newest superior build #442 (tried multiple dev builds from months ago too)

Im also still experiencing these issues.

**Comment by OmerBenGera** [comment]
I still can't replicate it myself
Were you able to replicate it on a server with only SSB installed? If so, what paper/spigot version you use? Send me the exact output of /version

**Comment by Yiiitt** [comment]
@OmerBenGera
Only SSB installed please check the video
https://youtu.be/_YsMNGm-7Sg

**Comment by Viivtor** [comment]
> [@OmerBenGera](https://github.com/OmerBenGera) Only SSB installed please check the video 0:23 https://youtu.be/_YsMNGm-7Sg?si=GwcwvC--h9IfZS5_&t=23

I asked someone on the BG-Software discord and they sent me an older DEV Build that works. Go search in the superiorskyblock2 channel and find the "SuperiorSkyblock2-2024.4-b369.jar" download link.

Conclusion: in dev build #369 no ghost blocks appear in generators.

**Comment by The-Jakub** [comment]
It happens to me too even if I only have SSB on the server:
Paper version 1.21.4-226-ver/1.21.4@a838a88
SuperiorSkyblock2-2025.1

**Comment by OmerBenGera** [comment]
Check out latest dev build, hopefully it is fixed

**Comment by AlFr3on111** [comment]
> Check out latest dev build, hopefully it is fixed

nope its not fixed sadly

**Comment by OmerBenGera** [comment]
Do you have ViaVersion?
Try removing it, see if it changes anything

**Comment by Viivtor** [comment]
> Do you have ViaVersion? Try removing it, see if it changes anything

I just tried removing ViaVersion with both 2025.1 and the 505 dev build.
I still experience the issue.

**Comment by AlFr3on111** [comment]
> Do you have ViaVersion? Try removing it, see if it changes anything

i did and still same issue

**Comment by ChenFangLing88** [comment]
please fix this error i also have this error and too many have had this error simply when you use high performance cup and press f3+t to mine for a long time i think you need to test many times because this error does not always happen

**Comment by RVSkeLe** [comment]
I can confirm this still happens in Purpur 1.21.4 and latest SSB2 dev build 523 with only ssb2 installed:
To reproduce I simply gave myself a eff 20 netherite pickaxe and mined for like 30 seconds
Pics: https://lunr.pics/fJ9W384Q, https://lunr.pics/SPHA2Mn1
Log: https://mclo.gs/gj8yWDl

**Comment by OmerBenGera** [comment]
what do you mean by speedtest?

**Comment by RVSkeLe** [comment]
> what do you mean by speedtest?

I needed to lag in order to replicate it atleast in decent times, I tried it for 15mins without being able to replicate it

**Comment by OmerBenGera** [comment]
Check out latest dev build, I changed some code and hopefully it fixes the issue

**Comment by RVSkeLe** [comment]
It's been 5 hours and the bug hasn't happened yet, seems like it's fixed

**Comment by RVSkeLe** [comment]
Seems like it's totally fixed for me!

**Comment by OmerBenGera** [comment]
Awesome
If the bug occurs again, let me know

**Comment by ChenFangLing88** [comment]
> Tuyệt vời Nếu lỗi xảy ra một lần nữa, hãy cho tôi biết

Ghost block is gone on stone farm but it still appears on basalt farm
