### ISSUE TITLE
Issue with stacked blocks

### ISSUE THREAD

**Issue by RVSkeLe** [BG-Software-LLC/SuperiorSkyblock2#2402]
### Minecraft's Version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)

### Plugin's Version

SuperiorSkyblock2-2024.4-b442

### Describe the bug

Unfortunately I have no idea how to reproduce the issue, I just noticed the exception in the console logs. https://pastes.dev/TJSVXuIXvc

### To Reproduce

//

**Comment by OmerBenGera** [comment]
Not sure why it happened. I added debug messages in latest dev build with more information regarding this.
Test it out and report back if it happens again.

**Comment by RVSkeLe** [comment]
Update to b446 and got this https://pastes.dev/Tb4JAtB0Ne

**Comment by OmerBenGera** [comment]
> Updated to b446 and got this https://pastes.dev/Tb4JAtB0Ne

What did you place that caused this to occur?

**Comment by RVSkeLe** [comment]
I have no idea, I couldn't find the player who was placing blocks, I'll try to tp to all the players if I see the error again

**Comment by RVSkeLe** [comment]
I still haven't been able to identify the issue, but it'd probably be helpful to get the player's name

**Comment by OmerBenGera** [comment]
I added more debug messages, including the player's name and the block that was placed.

**Comment by RVSkeLe** [comment]
Ok with some more info in the debug message I was able to find the issue. The issue comes from another plugin (Elevators) https://pastes.dev/2ZEeldqwI6

**Comment by RVSkeLe** [comment]
> Can you send me a link to the plugin?

This is the plugin https://github.com/keehl254/Elevators (we're running the last commit since the public one has very heavy hoppers checks)

**Comment by OmerBenGera** [comment]
When I compile it, it's missing FoliaLib.
Can you send me exact instructions on how you compiled it / send me a compiled jar?

**Comment by RVSkeLe** [comment]
> When I compile it, it's missing FoliaLib. Can you send me exact instructions on how you compiled it / send me a compiled jar?

Uh that's weird, we just compiled it, here's the Jar on the latest commit: https://github.com/Kawi16/Elevators/releases/tag/v5.0.0-beta.9

**Comment by OmerBenGera** [comment]
Check out latest dev build, this should be fixed

**Comment by RVSkeLe** [comment]
Uh apparently it's not fixed https://pastes.dev/n0dFL7CX8t. The issue only happens when you place a single elevator, to reproduce:
1. elevators give name default
2. Place that elevator and the npe should occur

**Comment by RVSkeLe** [comment]
I just noticed that I forgot probably the most important detail, you must be in gms for the npe to occur

**Comment by Kawi16** [comment]
I encountered a priority issue: when the elevator size was set to 1, the amount was set to 0 in the BlockPlaceEvent and the item became null for SSB2.
I also submitted a pull request to the original developer to change the priority of the BlockPlaceEvent. With mine version (https://github.com/Kawi16/Elevators) there isn't this problem.

**Comment by OmerBenGera** [comment]
> I encountered a priority issue: when the elevator size was set to 1, the amount was set to 0 in the BlockPlaceEvent and the item became null for SSB2. I also submitted a pull request to the original developer to change the priority of the BlockPlaceEvent. With mine version (https://github.com/Kawi16/Elevators) there isn't this problem.

You're right, however fixing their priority is not the solution - it's a bug in SSB.
It should be fixed in latest dev build.

**Comment by RVSkeLe** [comment]
>  It should be fixed in latest dev build.

Yes it's fixed in the latest dev build, thanks once again for the great job! :)
