### ISSUE TITLE
Crops growth after changing island world

### ISSUE THREAD

**Issue by Lemvs** [BG-Software-LLC/SuperiorSkyblock2#2763]
### Minecraft's Version

1.21.10

### Plugin's Version

2025.2

### Describe the bug

If we enter another world and then return to the island, after a while crops stops growing. I set the value to 100 for the 4th level of crop-growth upgrade (rest configuration is default), before entering the nether and a few seconds after returning to the island the bamboos grow quickly, but suddenly they stop growing, `/is admin syncupgrades` solves the problem. The upgrade level does not change, the multiplier just stops working.

https://imgur.com/a/LXMPFxU

### To Reproduce

\-

**Comment by OmerBenGera** [comment]
Check out latest dev build, should be fixed

**Comment by Lemvs** [comment]
> Check out latest dev build, should be fixed

It's not fixed, now this feature completly doesn't work, I set the multiplier value even to 10000, nothing started growing, while when I changed the random tick speed to only 100 from the default 3, something started growing visually normally (tested on Paper 1.16.5) (On previous build it works correctly)

**Comment by OmerBenGera** [comment]
@Lemvs should be fixed as well, sorry about that

**Comment by Lemvs** [comment]
Fixed
