### ISSUE TITLE
Block stacking. 

### ISSUE THREAD

**Issue by Pikaronga** [BG-Software-LLC/SuperiorSkyblock2#315]
**Minecraft's Version**
Purpur 1.16.5

**Plugin's Version**: -
SuperiorSkyblock2-b169

**Describe the bug**
When using the rosestacker gui to stack blocks it allows visitors to change the stack. To fix this you would hook into rosestackers stacking gui. https://github.com/Rosewood-Development/RoseStacker

**To Reproduce**
Stack a block on your island and allow someone else to visit the island and they are able to change the stack.

**Additional information**
Pretty explanatory.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build :)

**Comment by Pikaronga** [comment]
> 
> 
> Fixed in latest dev build :)

IT isn't just tried it and still isn't protected.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build, sorry about that

**Comment by Pikaronga** [comment]
it isn't fixed tho? still doesn't work

**Comment by Pikaronga** [comment]
> 
> 
> Fixed in latest dev build, sorry about that

it isn't fixed tho? still doesn't work as of build SuperiorSkyblock2-b196.jar

**Comment by OmerBenGera** [comment]
Take a video of the issue please, as from my tests it worked fine. I might didn't understand exactly what the issue was...

**Comment by Pikaronga** [comment]
> Take a video of the issue please, as from my tests it worked fine. I might didn't understand exactly what the issue was...

https://youtu.be/3vNOEpBQrIw
(old video just showcasing the function) 
But when a user has a blockstack on their island and a visitor sneak presses the stack they can edit it. This is the problem.

**Comment by OmerBenGera** [comment]
I am sorry, but I can't seem to replicate the issue. I tried accessing a block using the sneak-click feature, and it blocked me from doing so. Maybe the visitor that tried to click the block on your server had the permission to edit blocks on that island, or he had /is admin bypass enabled (for example, if and admin tested it for you).

**Comment by Skizzles** [comment]
@Pikaronga is this issue still occurring or is it resolved?

**Comment by Pikaronga** [comment]
> 
> 
> I am sorry, but I can't seem to replicate the issue. I tried accessing a block using the sneak-click feature, and it blocked me from doing so. Maybe the visitor that tried to click the block on your server had the permission to edit blocks on that island, or he had /is admin bypass enabled (for example, if and admin tested it for you).

This is not fixed. As I have a alt with only default group permission. I place blocks on my main island. I visit the island with my alt and I can access the sneak click "gui". Even tho I am not a member of the island nor have admin perms.

**Comment by Pikaronga** [comment]
> 
> 
> @Pikaronga is this issue still occurring or is it resolved?

still occurring

**Comment by OmerBenGera** [comment]
What version of RoseStacker and SSB are you using?

**Comment by Pikaronga** [comment]
> 
> 
> What version of RoseStacker and SSB are you using?

SSB2: 209
RoseStacer: 1.3

**Comment by OmerBenGera** [comment]
I tested it again and it works flawlessly fine for me.
Unless you let me know how to replicate the issue, I can't do anything in order to fix it.
Try replicating it on a server with only these plugins installed.

**Comment by Pikaronga** [comment]
> 
> 
> I tested it again and it works flawlessly fine for me.
> Unless you let me know how to replicate the issue, I can't do anything in order to fix it.
> Try replicating it on a server with only these plugins installed.

Are you sure you are using their block-stacking gui and not your own? 

To replicate. 

1.16.5 Purpur. (Latest 1.16.5 build) 
SSB: 209
RoseStacker: 1.3

Place down diamond blocks to stack. Put more into them with the gui. 

Go to ur alt that has the default perms. 

Visit your mains island and you will be able to edit the stack without problem.

**Comment by OmerBenGera** [comment]
> 
> 
> > I tested it again and it works flawlessly fine for me.
> > Unless you let me know how to replicate the issue, I can't do anything in order to fix it.
> > Try replicating it on a server with only these plugins installed.
> 
> Are you sure you are using their block-stacking gui and not your own?
> 
> To replicate.
> 
> 1.16.5 Purpur. (Latest 1.16.5 build)
> SSB: 209
> RoseStacker: 1.3
> 
> Place down diamond blocks to stack. Put more into them with the gui.
> 
> Go to ur alt that has the default perms.
> 
> Visit your mains island and you will be able to edit the stack without problem.

Yes, I am sure their menu is the menu that I test...
I also checked the code and there's a check for sneaking and opening the menu, so I don't know what can cause it.

**Comment by Pikaronga** [comment]
> 
> 
> > > I tested it again and it works flawlessly fine for me.
> > > Unless you let me know how to replicate the issue, I can't do anything in order to fix it.
> > > Try replicating it on a server with only these plugins installed.
> > 
> > 
> > Are you sure you are using their block-stacking gui and not your own?
> > To replicate.
> > 1.16.5 Purpur. (Latest 1.16.5 build)
> > SSB: 209
> > RoseStacker: 1.3
> > Place down diamond blocks to stack. Put more into them with the gui.
> > Go to ur alt that has the default perms.
> > Visit your mains island and you will be able to edit the stack without problem.
> 
> Yes, I am sure their menu is the menu that I test...
> I also checked the code and there's a check for sneaking and opening the menu, so I don't know what can cause it.

that's odd. Then it makes no sense why it wouldn't work? but it surely doesn't. https://youtu.be/id2oH2e0Gyg

**Comment by OmerBenGera** [comment]
I don't know what the issue is, just add your blocks to the interactables file and it will work.
