### ISSUE TITLE
Players unable to create an Island

### ISSUE THREAD

**Issue by DuneSciFye** [BG-Software-LLC/SuperiorSkyblock2#321]
**Minecraft's Version**
Paper 1.17

**Plugin's Version**: -
Build 169

**Describe the bug**
All of my new players cannot create islands. They do /is create and choose an island type, and it says Processing request, but never creates an island. When you do /is or /is create, it says you already have an ongoing creation task. No error occurs in console, or any message. If they try to do /is go, it says You don't have an island. Trying to force visit or admin disband doesn't work either

**To Reproduce**
Use build 169 on Paper 1.17 and try to create an island

**Additional information**
![image](https://user-images.githubusercontent.com/65089425/123342913-a0e48c80-d51e-11eb-8999-acb42929ddb3.png)
![image](https://user-images.githubusercontent.com/65089425/123342923-a5a94080-d51e-11eb-8d00-e0bb8057e6da.png)

**Comment by DuneSciFye** [comment]
Hello, I also realized that the island creation menu says unavailable

![image](https://user-images.githubusercontent.com/65089425/123492420-714d8700-d5e7-11eb-9ddc-0c6b41c68a0f.png)

**Comment by OmerBenGera** [comment]
I had a similar issue with Paper 1.17. It works fine on regular Spigot 1.17 and Paper 1.16.5, which is weird.

**Comment by DuneSciFye** [comment]
It works on Spigot 1.17? Nice! I'm gonna switch to that until its patched for paper

**Comment by DuneSciFye** [comment]
I just switched to Spigot 1.17, and had my alt who doesn't have an island try to make one. It still said unavailable and this error occurred in console 
[error.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6720580/error.txt)

**Comment by DuneSciFye** [comment]
I tried using the stable release, 1.7.0, but it still said unavailable and this error
[error.txt](https://github.com/BG-Software-LLC/SuperiorSkyblock2/files/6720588/error.txt)

**Comment by OmerBenGera** [comment]
Upload the error to pastebin.

**Comment by DuneSciFye** [comment]
https://pastebin.com/Ry6r8GHG

**Comment by DuneSciFye** [comment]
Alright, so after much trial and error, I've narrowed it down that the issue is my database. With my current database, the error occurs. With a fresh database, it works fine. Here is my database download since I can't upload it here https://www.mediafire.com/file/5l8c38o6k79rskb/database.db/file

**Comment by OmerBenGera** [comment]
> Alright, so after much trial and error, I've narrowed it down that the issue is my database. With my current database, the error occurs. With a fresh database, it works fine. Here is my database download since I can't upload it here https://www.mediafire.com/file/5l8c38o6k79rskb/database.db/file

This has nothing to do with your database.
Its a known issue and hopefully I will be able to get it fixed by the end of the week. I might be wrong, but I am pretty sure the error is an issue with Spigot and not the plugin itself. Try updating your spigot jar

**Comment by OmerBenGera** [comment]
I also fixed the paper bug, so try updating to Paper.

**Comment by DuneSciFye** [comment]
I updated to latest paper build, and used dev build 173, but it still doesn't work. It just says Processing your request...

**Comment by DuneSciFye** [comment]
Hello, it's been 2 days and I was wondering if this issue has been fixed yet

**Comment by OmerBenGera** [comment]
> Hello, it's been 2 days and I was wondering if this issue has been fixed yet

No... its only been 2 days, I havent been at home yet.
Be patient, I am not working on the plugins full-time

**Comment by Kamology** [comment]
Just wanted to confirm I'm experiencing this also. No errors, just an indefinite island creation hang. Resetting database does nothing. Paper 1.17-68 SSB2-b173

**Comment by Skizzles** [comment]
Tested this on dev build 173 and receive:
https://pastebin.com/45jFQW4P

@DuneSciFye please be sure to post warns/errors received as those can speed up the process incredibly.

**Comment by Ibesh** [comment]
> Just wanted to confirm I'm experiencing this also. No errors, just an indefinite island creation hang. Resetting database does nothing. Paper 1.17-68 SSB2-b173

I am also experiencing the same on issue on Tuinity 1.17, just so you are aware. 

Tuinity 1.17-7
SSB2-b175

**Comment by OmerBenGera** [comment]
Seems to work fine for me with latest Tuniity version and latest SSB dev build.

**Comment by OmerBenGera** [comment]
I could replicate the issue with Tuinity as well, gonna check that out.
It works fine with regular Spigot and Paper, so for now you can use them until it's patched.

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build (176)
Let me know if it works for you

**Comment by DuneSciFye** [comment]
It now works, pog!

**Comment by Kamology** [comment]
Yep we good now on Paper, thanks so much

**Comment by OmerBenGera** [comment]
I am closing this as it seems to work at this moment.
If it happens again, make sure you reopen the issue :)

**Comment by riderovsky** [comment]
I have the same problem now, newest dev and minecraft 1.8.8 paperspigot.

**Comment by OmerBenGera** [comment]
> 
> 
> I have the same problem now, newest dev and minecraft 1.8.8 paperspigot.

Open a new issue, this issue was closed 4 months ago.
