### ISSUE TITLE
Slimefun Integration Needs Updated

### ISSUE THREAD

**Issue by Skizzles** [BG-Software-LLC/SuperiorSkyblock2#578]
### Minecraft's Version

1.17.1 purpur dev 1375

### Plugin's Version

dev 295

### Describe the bug

Slimefun had a major update which changes multiple things, SSB throws errors now due to these changes.

### To Reproduce

https://github.com/Slimefun/Slimefun4/pull/3139

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build

**Comment by OmerBenGera** [comment]
Have you tried it?

**Comment by kizoukun** [comment]
Still doesn't work with latest dev build 1.7.0-DEVb302
show this error https://pastebin.com/WeFfXtDd and player still can access slimefun item on others island

**Comment by OmerBenGera** [comment]
Fixed in latest dev build @kizoukun
