### ISSUE TITLE
Breka Pumpkin is under "interact"

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/SuperiorSkyblock2#697]
### Minecraft's Version

1.16.5 Airplane

### Plugin's Version

b336

### Describe the bug

To break a pumpkin, player need the "interact" permission, it shouldn't.
For everyblock player need the "block break" permission, but for pumpkin, he also need "interact" permission

### To Reproduce

- Set break-block to visitor
- Place a dirt and a pumpkin
- Ask visitor to break both, he can only break dirt.
- Set "interact" to visitor
- Now he can break pumpkin

**Comment by OmerBenGera** [comment]
The pumpkin block might be under the `interactables.yml` file, which makes the plugin require players to have the INTERACT permission. The issue is why it's there probably, and I believe without that players can curve it on other islands.

I will look into that and get back to you.

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by WarnDa** [comment]
Not fixed on latest dev build
<img width="417" alt="Screenshot_6949" src="https://user-images.githubusercontent.com/31826333/140595891-f869696e-7f6c-4073-a687-c9d1dd1547be.png">

Player tried to destroy pumpkin using a diamond axe.
Didn't work unless I set "interact" permission to true

**Comment by OmerBenGera** [comment]
Should be fixed in latest dev build
Update me after you test it.

**Comment by OmerBenGera** [comment]
Have you tested it?

**Comment by WarnDa** [comment]
Fixed !
