### ISSUE TITLE
Farming Missions

### ISSUE THREAD

**Issue by LeAnhTuan0810** [BG-Software-LLC/SuperiorSkyblock2#762]
### Minecraft's Version

Minecraft Version: 1.17.1

### Plugin's Version

SuperiorSkyblock2-1.8.2-b382

### Session Logs

.

### Describe the bug

https://paste.sparked.host/kitoxevepi.coffeescript
When I do missions **required-plants: MELON** it doesn't work
Inactive plants **Melon, Pumpkin, Bamboo**

### To Reproduce

.

**Comment by LeAnhTuan0810** [comment]
Update: Inactive plants **OAK_SAPLING, SPRUCE_SAPLING, BIRCH_SAPLING, JUNGLE_SAPLING, ACACIA_SAPLING, DARK_OAK_SAPLING**

**Comment by OmerBenGera** [comment]
Try MELON_BLOCK maybe?

**Comment by LeAnhTuan0810** [comment]
still not working

**Comment by LeAnhTuan0810** [comment]
You can check the plants: Melon, Pumpkin, Bamboo, Oak Sapling, Spruce Sapling, Birch Sapling, Jungle Sapling, Acacia Sapling and Dark Oak Sapling

**Comment by ST3RmY** [comment]
i have the same problem with melons and beetroots.

remove unconfirmed tag and fix bugs.

TIP: I am using paper 1.12.2 and the latest stable version of SBlock

**Comment by OmerBenGera** [comment]
> i have the same problem with melons , wheats and beetroots.
> 
> remove unconfirmed tag and fix bugs.
> 
> TIP: I am using paper 1.12.2 and the latest stable version of SBlock

I will remove the unconfirmed bug once I can **confirm** that the bug happens.
Be patient, it won't kill you.

**Comment by OmerBenGera** [comment]
I fixed some issues, added support for trees and bamboo.
Here is my mission and all the listed plants worked for me:
https://pastebin.com/LAfE15c6

Make sure you are the one that planting the crops again, as farming missions will only work on plants that you planted!

**Comment by ST3RmY** [comment]
i'll try

**Comment by ST3RmY** [comment]
Pumpkins and melons still don't work, pumpkins only work for me if there are only them in the mission, if I add more they don't work anymore and I don't understand the meaning.

Instead the melons never go

**Comment by ST3RmY** [comment]
I tried missions and now your file does not even work carrots and potatoes that works before ...

There are many problems in agricultural missions.


and I take this opportunity to report that BrewingMissions is not working, it is not loaded

**Comment by OmerBenGera** [comment]
> I tried missions and now your file does not even work carrots and potatoes that works before ...
> 
> There are many problems in agricultural missions.
> 
> and I take this opportunity to report that BrewingMissions is not working, it is not loaded

You are probably doing something wrong, as the mission file that I sent on latest dev build works flawlessly fine.
Make sure you are the one that plants the crops (replant them) and test it on a server where only SSB installed.

**Comment by ST3RmY** [comment]
I'm not doing anything wrong.

And I am using SSB on a server where only SSB and worldedit is.

There is some problem with the plugin.

**Comment by OmerBenGera** [comment]
> I'm not doing anything wrong.
> 
> And I am using SSB on a server where only SSB and worldedit is.
> 
> There is some problem with the plugin.

Let me know how to replicate the issue, as it works fine for me. Also, take a video of the issue - show how you plant the crop, let it grow and that it doesnt work.

**Comment by ST3RmY** [comment]
As soon as I have time I will make the video, where can I send it?

**Comment by OmerBenGera** [comment]
> As soon as I have time I will make the video, where can I send it?

Via youtube or any other online streaming service.

**Comment by OmerBenGera** [comment]
@ST3RmY Any news regarding this?

**Comment by warzoneak** [comment]
You asked me to post here. Im also having this issue.

Server is not tracking any growth for farmingmissions. Mining and others work fine just farming.

I've attached a video showing a default install no other plugins and it not working.

Server Version is Paper 1.12.2 and no errors at all in console

Video: https://youtu.be/9AdFODWqiEA

**Comment by JLucassz** [comment]
I'm having this problem with wheat, potato, carrot and beet crops as well.

**Comment by OmerBenGera** [comment]
@warzoneak Upload your farming mission file
@JLucassz Version of minecraft? also, upload your farming missions file.

**Comment by warzoneak** [comment]
Here is the farming config, I did try using Carrot_Item and Potato_Item cause im using 1.12.2 but that didnt work. Other then that this is the default farmer_1 i have made no changes as showed in the youtube link

https://pastebin.com/c96dyqZK

**Comment by OmerBenGera** [comment]
I tested it on 1.12.2 Paper and it works flawlessly fine.
@warzoneak Your config has wrong materials and you use incorrect formatting. You can see my version for 1.12 that worked for me:
https://pastebin.com/9SwZnXdD

**Comment by JLucassz** [comment]
I'm using minecraft version 1.17.1. The crops of carrots, potatoes, wheat and beetroot are not working. I am also using stable version 1.8.3 of the plugin.

https://paste.denizenscript.com/View/91758

**Comment by OmerBenGera** [comment]
@JLucassz I tested your config file on 1.17.1 and it works fine.
I removed the required mission and then I plant the crops. After they grow, I get the progress without breaking the plants or anything like that.
I think you're doing something wrong, as it works fine for me.

**Comment by Davisiiiik** [comment]
Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
Plugin: 1.8.4.496

For me Melons and Pumpkins dont count, when they are in the mission alone (mission only for melon and mission only for pumpkin dont work). If they are together in one mission, they work fine. I digged a little in source code. Arent the rows 205 and 208 switched?

![image](https://user-images.githubusercontent.com/79375965/151641642-9a2daebc-f5e8-4a9c-a4db-d14282e95cb6.png)

**Comment by ripperfame1** [comment]
we have figured out that island missions do not reset. For farming missions you have to hold "500" of said items "Wheat,pumpkin,potatoes" in inventory once u take out of inventory the count goes to 0
once the missions is claimed it will take "500" of those items and you'll be able to complete the missions

**Comment by ripperfame1** [comment]
@LeAnhTuan0810

**Comment by OmerBenGera** [comment]
> we have figured out that island missions do not reset. For farming missions you have to hold "500" of said items "Wheat,pumpkin,potatoes" in inventory once u take out of inventory the count goes to 0 once the missions is claimed it will take "500" of those items and you'll be able to complete the missions

Farming missions do not care how many items you have in your inventory. They track the data when a crop that you planted grew to its final stage.

**Comment by Davisiiiik** [comment]
> > Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475) Plugin: 1.8.4.496
> > For me Melons and Pumpkins dont count, when they are in the mission alone (mission only for melon and mission only for pumpkin dont work). If they are together in one mission, they work fine. I digged a little in source code. Arent the rows 205 and 208 switched?
> > ![image](https://user-images.githubusercontent.com/79375965/151641642-9a2daebc-f5e8-4a9c-a4db-d14282e95cb6.png)
> 
> This has been fixed.
> 
> @LeAnhTuan0810 I would update and see if the issue still occurs for Melon/Pumpkin

I know, I submitted that issue today.

**Comment by OmerBenGera** [comment]
This is fixed in latest dev build.
If it happens again, let me know :)
