### ISSUE TITLE
/is level - Error

### ISSUE THREAD

**Issue by itslukemango** [BG-Software-LLC/SuperiorSkyblock2#788]
### Minecraft's Version

![image](https://user-images.githubusercontent.com/29614155/146686059-b59d2cbc-54bf-4427-b923-c9b88196b66c.png)

### Plugin's Version

![image](https://user-images.githubusercontent.com/29614155/146686069-ca0838ec-3b48-44dd-9c48-30007c7bf645.png)

### Describe the bug

/is level - spams console
![image](https://user-images.githubusercontent.com/29614155/146686077-b80fe823-0edc-4ece-913a-880c1afe5687.png)
https://pastebin.com/LkPeC7sv

### To Reproduce

Type /is level

**Comment by OmerBenGera** [comment]
I will look into it.
For now you can downgrade to an older dev build.

**Comment by OmerBenGera** [comment]
Fixed in latest build

**Comment by itslukemango** [comment]
https://pastebin.com/bCkynS9j - not fixed on latest dev build

**Comment by itslukemango** [comment]
@OmerBenGera https://pastebin.com/bCkynS9j - not fixed on latest dev build

**Comment by OmerBenGera** [comment]
> @OmerBenGera https://pastebin.com/bCkynS9j - not fixed on latest dev build

This is not related to the issue.
This issue is due to your nashorn engine having issues.
You can see my response to a similar issue here:
https://github.com/BG-Software-LLC/SuperiorSkyblock2/issues/371#issuecomment-996608545
