### ISSUE TITLE
Reset island

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/SuperiorSkyblock2#873]
### Minecraft's Version

1.18.1

### Plugin's Version

b484

### Describe the bug

Hello, when i start the server, create new island, after restart the island isn't exist and i'm teleport to the spawn because : "The island isn't exist".

### To Reproduce

Create new island and restart the server.

**Comment by nivcoo** [comment]
I've check the db and if after the restart i create new island i've 2 island in db https://pics.revolis.fr/2022/01/23/15-30_jDBo.png , maybe the loading not works correctly

**Comment by OmerBenGera** [comment]
Look for errors when you create the island.

**Comment by nivcoo** [comment]
0 error in console

**Comment by OmerBenGera** [comment]
> 0 error in console

Try replicating the issue on another server with only SSB installed using default files.

**Comment by nivcoo** [comment]
It works correctly if i back the version of SS2

**Comment by OmerBenGera** [comment]
> It works correctly if i back the version of SS2

Ah I see.
What version does it work on?

**Comment by nivcoo** [comment]
Previously the update of ss2 i was on version before rewrite of db, idk exactly the build

**Comment by Trinchezito** [comment]
When you update from Build #469 to Build #470 + the island database breaks. 
It also doesn't connect you to MySQL server. So basically the last working build is Build #469

**Comment by nivcoo** [comment]
> When you update from Build #469 to Build #470 + the island database breaks. It also doesn't connect you to MySQL server. So basically the last working build is Build #469.
> 
> I also can confirm this is an issue after build #469. The plugin acts like it doesn't read the database, so every time someone logs out of the server, they lose their data and need to create a new island. There are about 3+ issues regarding this.

Yes it's that thx :p

**Comment by OmerBenGera** [comment]
> When you update from Build #469 to Build #470 + the island database breaks. It also doesn't connect you to MySQL server. So basically the last working build is Build #469.
> 
> I also can confirm this is an issue after build #469. The plugin acts like it doesn't read the database, so every time someone logs out of the server, they lose their data and need to create a new island. There are about 3+ issues regarding this.

When it's not connecting you to MySQL, what error does it give?

**Comment by OmerBenGera** [comment]
Should be fixed on latest dev build for SQLite, MySQL and any other database type.
Let me know if it works

**Comment by Trinchezito** [comment]
> 

Yes, it works now.

I still get an error, not sure what is it about and if it can be ignored or not.

`Caused by: java.lang.NullPointerException: Couldn't find an IslandPrivilege with the name check_permission.`



Complete error:


`[SuperiorSkyblock2] Successfully loaded schematic islanddessert.schematic (DefaultSchematicParser)
[21:05:35] [Server thread/WARN]: com.bgsoftware.superiorskyblock.handler.HandlerLoadException: java.lang.NullPointerException: Couldn't find an IslandPrivilege with the name check_permission.
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.handleExceptions(MenusProvider_Default.java:72)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.initializeMenus(MenusProvider_Default.java:107)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.menu.MenusHandler.loadData(MenusHandler.java:26)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.reloadPlugin(SuperiorSkyblockPlugin.java:490)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.SuperiorSkyblockPlugin.onEnable(SuperiorSkyblockPlugin.java:270)
[21:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[21:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[21:05:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[21:05:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[21:05:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:736)
[21:05:35] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:353)
[21:05:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1233)
[21:05:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322)
[21:05:35] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[21:05:35] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Couldn't find an IslandPrivilege with the name check_permission.
[21:05:35] [Server thread/WARN]: 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:895)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.api.island.IslandPrivilege.getByName(IslandPrivilege.java:36)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.menu.impl.MenuIslandPrivileges.init(MenuIslandPrivileges.java:101)
[21:05:35] [Server thread/WARN]: 	at SuperiorSkyblock2-1.8.3-b485.jar//com.bgsoftware.superiorskyblock.hooks.provider.MenusProvider_Default.handleExceptions(MenusProvider_Default.java:70)
[21:05:35] [Server thread/WARN]: 	... 14 more
[21:05:35] [Server thread/ERROR]: (com.mysql.jdbc.Driver:43) Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[21:05:35] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Starting...
[21:05:35] [Server thread/WARN]: [com.bgsoftware.superiorskyblock.libs.hikari.util.DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[21:05:35] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Start completed.
[21:05:35] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Shutdown initiated...
[21:05:35] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Shutdown completed.
[21:05:35] [Server thread/INFO]: [SuperiorSkyblock2] Trying to connect to remote database (MySQL)...
[21:05:35] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Starting...
[21:05:35] [Server thread/WARN]: [com.bgsoftware.superiorskyblock.libs.hikari.util.DriverDataSource] Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[21:05:35] [Server thread/INFO]: [com.bgsoftware.superiorskyblock.libs.hikari.HikariDataSource] SuperiorSkyblock Pool - Start completed.
[21:05:35] [Server thread/INFO]: [SuperiorSkyblock2] Successfully established connection with remote database!`

**Comment by nivcoo** [comment]
I have the same error, now this permission doesnt exist, si just delete it, maybe it a forgiven ? Idk

**Comment by OmerBenGera** [comment]
@nivcoo @Trinchezito delete `check_psrmission` from the permissions menu - this permission no longer in use.
Anyways, closing this issue :)

**Comment by nivcoo** [comment]
Hello,i've tried and isn't fixed : https://pastebin.com/Wjcedgn2

**Comment by nivcoo** [comment]
I've tried to delete my DB and my world and satrt the server and same issue after the second restart

**Comment by OmerBenGera** [comment]
> Hello,i've tried and isn't fixed : https://pastebin.com/Wjcedgn2

Your sqlite file is locked and it has nothing to do with the issue above.
Make sure nothing else locks the database so SSB can interact with it.
Make sure you delete the journal file as well.

**Comment by nivcoo** [comment]
> > Hello,i've tried and isn't fixed : https://pastebin.com/Wjcedgn2
> 
> Your sqlite file is locked and it has nothing to do with the issue above. Make sure nothing else locks the database so SSB can interact with it. Make sure you delete the journal file as well.

My island is reset due to that so yes it's the same issue

**Comment by nivcoo** [comment]
Like before, if i back the version it works so it's a recent issue

**Comment by OmerBenGera** [comment]
> > > Hello,i've tried and isn't fixed : https://pastebin.com/Wjcedgn2
> > 
> > 
> > Your sqlite file is locked and it has nothing to do with the issue above. Make sure nothing else locks the database so SSB can interact with it. Make sure you delete the journal file as well.
> 
> My island is reset due to that so yes it's the same issue

The database file is locked, this is why it occurs.

**Comment by nivcoo** [comment]
Thanks you

**Comment by OmerBenGera** [comment]
@nivcoo Check out latest dev build, hopefully everything is fixed now

**Comment by nivcoo** [comment]
> @nivcoo Check out latest dev build, hopefully everything is fixed now

It works, thx :p
